export const freedie = [
    {
        id:'Daniel-Panjwaneey',
        name:'Daniel Panjwaneey',
        imgSrc:'src/assets/freedi/466618437_10162709052786002_3053336421370686286_n.jpg',
        desc:"Daniel Arthur Panjwaneey is a multifaceted creative force from Karachi, Pakistan, with extensive experience as a Producer, Curator, and Audio Engineer. Renowned for his innovative approach to music and sound, he is also celebrated as Alien Panda Jury, his avant-garde musical alias, and Kukido, a testament to his culinary prowess as a professional cook. A former bassist for the acclaimed band The D/A Method, Daniel's diverse talents and passion for creativity make him a dynamic figure in both the arts and gastronomy.",
        role:'Producer/Curator/Audio-Engineer',
        eMail:'wuTang@methodman.com',
        phone:'+92-0900-78601',
        fb:'https://www.facebook.com/danielpanjwaneey',
        insta:'https://www.instagram.com/alienpandajury.kukido/',
        x:'https://www.facebook.com/danielpanjwaneey',
        linkedIn:'https://www.facebook.com/danielpanjwaneey',
        spotify:'https://open.spotify.com/artist/6OfjFTS57bjf89tHhKTLgi?si=HNGhtYN7RquxjUp7c1nSpg',
        linktree:'https://linktr.ee/alienpandajury',
        youtube:'https://www.youtube.com/playlist?list=PL5Ryp-hMdvtHIGjgXtZCY4cLDkHhdSPNf',
        soundcloud:'https://soundcloud.com/alienpandajury',
        bandcamp:'https://alienpandajury.bandcamp.com/'
    },
    {
        id:'Saqlain-Haider',
        name:'Saqlain Haider',
        imgSrc:'src/assets/freedi/WhatsApp Image 2025-01-14 at 00.18.56_bfd3047e.jpg',
        desc:"Saqlain Haider is a highly accomplished developer specializing in UI/UX and creating high-performing, 3D interactive websites. A visionary leader, he has won international awards for websites he built and managed with his team. As the former COO of a company he co-founded, Saqlain played a pivotal role in growing it into a thriving business offering top-tier front-end services. Beyond tech, he has been the lead guitarist for multiple bands, showcasing his artistic talent, and he also passionately explores the fascinating world of mycology.",
        role:'Software-Engineer/ UI/UX /Musician/Mycology',
        eMail:'wuTang@methodman.com',
        phone:'+92-0900-78601',
        fb:'https://www.facebook.com/saqlainh3/',
        insta:'https://www.instagram.com/svqlvin_dp_hvider/',
        x:'https://www.instagram.com/svqlvin_dp_hvider/',
        linkedIn:'https://www.linkedin.com/in/saqlainhaider77/',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:''
    },
    {
        id:'Daniel-Panjwaneey',
        name:'Daniel Panjwaneey',
        imgSrc:'src/assets/freedi/466618437_10162709052786002_3053336421370686286_n.jpg',
        desc:"Daniel Arthur Panjwaneey is a multifaceted creative force from Karachi, Pakistan, with extensive experience as a Producer, Curator, and Audio Engineer. Renowned for his innovative approach to music and sound, he is also celebrated as Alien Panda Jury, his avant-garde musical alias, and Kukido, a testament to his culinary prowess as a professional cook. A former bassist for the acclaimed band The D/A Method, Daniel's diverse talents and passion for creativity make him a dynamic figure in both the arts and gastronomy.",
        role:'Producer/Curator/Audio-Engineer',
        eMail:'wuTang@methodman.com',
        phone:'+92-0900-78601',
        fb:'https://www.facebook.com/danielpanjwaneey',
        insta:'https://www.instagram.com/alienpandajury.kukido/',
        x:'https://www.facebook.com/danielpanjwaneey',
        linkedIn:'https://www.facebook.com/danielpanjwaneey',
        spotify:'https://open.spotify.com/artist/6OfjFTS57bjf89tHhKTLgi?si=HNGhtYN7RquxjUp7c1nSpg',
        linktree:'https://linktr.ee/alienpandajury',
        youtube:'https://www.youtube.com/playlist?list=PL5Ryp-hMdvtHIGjgXtZCY4cLDkHhdSPNf',
        soundcloud:'https://soundcloud.com/alienpandajury',
        bandcamp:'https://alienpandajury.bandcamp.com/'
    },
    {
        id:'Saqlain-Haider',
        name:'Saqlain Haider',
        imgSrc:'src/assets/freedi/WhatsApp Image 2025-01-14 at 00.18.56_bfd3047e.jpg',
        desc:"Saqlain Haider is a highly accomplished developer specializing in UI/UX and creating high-performing, 3D interactive websites. A visionary leader, he has won international awards for websites he built and managed with his team. As the former COO of a company he co-founded, Saqlain played a pivotal role in growing it into a thriving business offering top-tier front-end services. Beyond tech, he has been the lead guitarist for multiple bands, showcasing his artistic talent, and he also passionately explores the fascinating world of mycology.",
        role:'Software-Engineer/ UI/UX /Musician/Mycology',
        eMail:'wuTang@methodman.com',
        phone:'+92-0900-78601',
        fb:'https://www.facebook.com/saqlainh3/',
        insta:'https://www.instagram.com/svqlvin_dp_hvider/',
        x:'https://www.instagram.com/svqlvin_dp_hvider/',
        linkedIn:'https://www.linkedin.com/in/saqlainhaider77/',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:''
    },
    {
        id:'Daniel-Panjwaneey',
        name:'Daniel Panjwaneey',
        imgSrc:'src/assets/freedi/466618437_10162709052786002_3053336421370686286_n.jpg',
        desc:"Daniel Arthur Panjwaneey is a multifaceted creative force from Karachi, Pakistan, with extensive experience as a Producer, Curator, and Audio Engineer. Renowned for his innovative approach to music and sound, he is also celebrated as Alien Panda Jury, his avant-garde musical alias, and Kukido, a testament to his culinary prowess as a professional cook. A former bassist for the acclaimed band The D/A Method, Daniel's diverse talents and passion for creativity make him a dynamic figure in both the arts and gastronomy.",
        role:'Producer/Curator/Audio-Engineer',
        eMail:'wuTang@methodman.com',
        phone:'+92-0900-78601',
        fb:'https://www.facebook.com/danielpanjwaneey',
        insta:'https://www.instagram.com/alienpandajury.kukido/',
        x:'https://www.facebook.com/danielpanjwaneey',
        linkedIn:'https://www.facebook.com/danielpanjwaneey',
        spotify:'https://open.spotify.com/artist/6OfjFTS57bjf89tHhKTLgi?si=HNGhtYN7RquxjUp7c1nSpg',
        linktree:'https://linktr.ee/alienpandajury',
        youtube:'https://www.youtube.com/playlist?list=PL5Ryp-hMdvtHIGjgXtZCY4cLDkHhdSPNf',
        soundcloud:'https://soundcloud.com/alienpandajury',
        bandcamp:'https://alienpandajury.bandcamp.com/'
    },
    {
        id:'Saqlain-Haider',
        name:'Saqlain Haider',
        imgSrc:'src/assets/freedi/WhatsApp Image 2025-01-14 at 00.18.56_bfd3047e.jpg',
        desc:"Saqlain Haider is a highly accomplished developer specializing in UI/UX and creating high-performing, 3D interactive websites. A visionary leader, he has won international awards for websites he built and managed with his team. As the former COO of a company he co-founded, Saqlain played a pivotal role in growing it into a thriving business offering top-tier front-end services. Beyond tech, he has been the lead guitarist for multiple bands, showcasing his artistic talent, and he also passionately explores the fascinating world of mycology.",
        role:'Software-Engineer/ UI/UX /Musician/Mycology',
        eMail:'wuTang@methodman.com',
        phone:'+92-0900-78601',
        fb:'https://www.facebook.com/saqlainh3/',
        insta:'https://www.instagram.com/svqlvin_dp_hvider/',
        x:'https://www.instagram.com/svqlvin_dp_hvider/',
        linkedIn:'https://www.linkedin.com/in/saqlainhaider77/',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:''
    },
    {
        id:'Daniel-Panjwaneey',
        name:'Daniel Panjwaneey',
        imgSrc:'src/assets/freedi/466618437_10162709052786002_3053336421370686286_n.jpg',
        desc:"Daniel Arthur Panjwaneey is a multifaceted creative force from Karachi, Pakistan, with extensive experience as a Producer, Curator, and Audio Engineer. Renowned for his innovative approach to music and sound, he is also celebrated as Alien Panda Jury, his avant-garde musical alias, and Kukido, a testament to his culinary prowess as a professional cook. A former bassist for the acclaimed band The D/A Method, Daniel's diverse talents and passion for creativity make him a dynamic figure in both the arts and gastronomy.",
        role:'Producer/Curator/Audio-Engineer',
        eMail:'wuTang@methodman.com',
        phone:'+92-0900-78601',
        fb:'https://www.facebook.com/danielpanjwaneey',
        insta:'https://www.instagram.com/alienpandajury.kukido/',
        x:'https://www.facebook.com/danielpanjwaneey',
        linkedIn:'https://www.facebook.com/danielpanjwaneey',
        spotify:'https://open.spotify.com/artist/6OfjFTS57bjf89tHhKTLgi?si=HNGhtYN7RquxjUp7c1nSpg',
        linktree:'https://linktr.ee/alienpandajury',
        youtube:'https://www.youtube.com/playlist?list=PL5Ryp-hMdvtHIGjgXtZCY4cLDkHhdSPNf',
        soundcloud:'https://soundcloud.com/alienpandajury',
        bandcamp:'https://alienpandajury.bandcamp.com/'
    },
    {
        id:'Saqlain-Haider',
        name:'Saqlain Haider',
        imgSrc:'src/assets/freedi/WhatsApp Image 2025-01-14 at 00.18.56_bfd3047e.jpg',
        desc:"Saqlain Haider is a highly accomplished developer specializing in UI/UX and creating high-performing, 3D interactive websites. A visionary leader, he has won international awards for websites he built and managed with his team. As the former COO of a company he co-founded, Saqlain played a pivotal role in growing it into a thriving business offering top-tier front-end services. Beyond tech, he has been the lead guitarist for multiple bands, showcasing his artistic talent, and he also passionately explores the fascinating world of mycology.",
        role:'Software-Engineer/ UI/UX /Musician/Mycology',
        eMail:'wuTang@methodman.com',
        phone:'+92-0900-78601',
        fb:'https://www.facebook.com/saqlainh3/',
        insta:'https://www.instagram.com/svqlvin_dp_hvider/',
        x:'https://www.instagram.com/svqlvin_dp_hvider/',
        linkedIn:'https://www.linkedin.com/in/saqlainhaider77/',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:''
    },
]