export const freedie = [
    {
        id:'Daniel-Panjwaneey',
        name:'Daniel Panjwaneey',
        imgSrc:'./dan.jpg',
        desc:"establishing himself as a creative force in audio production and engineering. From 2010 to 2014, Daniel was part of the globally acclaimed Coke Studio (Pakistan) during seasons 4, 5, and 6, where he contributed as an assistant audio engineer. His expertise further flourished as the Chief Audio Engineer at A for Aleph from 2016 to 2021. In 2021, Daniel founded Cape Monze Records, an independent label that reflects his passion for discovering and nurturing talent. ",
        role:'Producer/Curator/Audio-Engineer',
        eMail:'someemmail@com.mailg',
        fb:'https://www.facebook.com/danielpanjwaneey',
        insta:'https://www.instagram.com/alienpandajury.kukido/',
        x:'https://www.facebook.com/danielpanjwaneey',
        linkedIn:'https://www.facebook.com/danielpanjwaneey',
        spotify:'https://open.spotify.com/artist/6OfjFTS57bjf89tHhKTLgi?si=HNGhtYN7RquxjUp7c1nSpg',
        linktree:'https://linktr.ee/alienpandajury',
        youtube:'https://www.youtube.com/playlist?list=PL5Ryp-hMdvtHIGjgXtZCY4cLDkHhdSPNf',
        soundcloud:'https://soundcloud.com/alienpandajury',
        bandcamp:'https://alienpandajury.bandcamp.com/',
        github:''
    },
    {
        id:'Saqlain-Haider',
        name:'Saqlain Haider',
        imgSrc:'./saq.jpg',
        desc:"Saqlain Haider is a highly accomplished developer specializing in UI/UX and creating high-performing, 3D interactive websites. A visionary leader, he has won international awards for websites he built and managed with his team. As the former COO of a company he co-founded, Saqlain played a pivotal role in growing it into a thriving business offering top-tier front-end services. Beyond tech, he has been the lead guitarist for multiple bands, showcasing his artistic talent, and he also passionately explores the fascinating world of mycology.",
        role:'Software-Engineer/ UI/UX /Musician/Mycology',
        eMail:'saqlainhaider77@gmail.com',
        fb:'https://www.facebook.com/saqlainh3/',
        insta:'https://www.instagram.com/svqlvin_dp_hvider/',
        x:'https://www.instagram.com/svqlvin_dp_hvider/',
        linkedIn:'https://www.linkedin.com/in/saqlainhaider77/',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:'',
        github:'https://github.com/Saqman77'
    },
    {
        id:'Amna-Ali',
        name:'Amna Ali',
        imgSrc:'./Amna Ali.jpeg',
        desc:"Amna Ali is a freelance graphic designer with a passion for creating visually striking designs that tell a story. She specializes in logo design, branding, and digital illustrations, combining creativity and technical expertise to bring ideas to life. Through close collaboration with clients, she strives to understand their vision and craft designs that truly resonate with their audience.\nOver the years, Amna has had the privilege of working with businesses from various industries to build memorable visual identities. When not designing, she dedicates time to exploring the latest design trends and honing her skills to stay inspired and ahead of the curve.",
        role:'Graphic designer',
        eMail:'aamna9318@gmail.com',
        fb:'',
        insta:'',
        x:'',
        linkedIn:'',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:'',
        github:'',
        behance:'https://www.behance.net/amnaali51'
    },
    {
        id:'Usman-Mehmood',
        name:'Usman Mehmood',
        imgSrc:'',
        desc:"",
        role:'Electrical Engineer',
        eMail:'someemmail@com.mailg',
        // phone:'+92-0900-78601',
        fb:'https://www.facebook.com/saqlainh3/',
        insta:'https://www.instagram.com/svqlvin_dp_hvider/',
        x:'https://www.instagram.com/svqlvin_dp_hvider/',
        linkedIn:'https://www.linkedin.com/in/saqlainhaider77/',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:'',
        github:'https://github.com/Saqman77'
    },
    {
        id:'Beenish-Sarfaraz',
        name:'Beenish Sarfaraz',
        imgSrc:'',
        desc:"Beenish Sarfaraz is a visual artist and educator based in Karachi, Pakistan. Her interest lies in cultural and heritage stories, environment and social-engaged art making. Currently, she is a faculty member at Beaconhouse National University. Previously, she has worked on projects with Coke Studio (2018), Geo TV Network, Centre of Arts-based Methodologies and Wellbeing, British Council, State Bank Museum-Pakistan, Manchester Museum, ShirkatGah and DAWN. She uses inquiry and play as her method of research.",
        role:'Graphic Designer/Creative Non-fiction Writer ',
        eMail:'beenish.s.ali@gmail.com',
        // phone:'+92-0900-78601',
        fb:'https://www.facebook.com/saqlainh3/',
        insta:'https://www.instagram.com/svqlvin_dp_hvider/',
        x:'https://www.instagram.com/svqlvin_dp_hvider/',
        linkedIn:'https://www.linkedin.com/in/saqlainhaider77/',
        spotify:'',
        linktree:'',
        youtube:'',
        soundcloud:'',
        bandcamp:'',
        github:'',
        default:'https://beenishsarfaraz.cargo.site/'
    },
    
]